version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - database

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: BoisdeCen2&*
      MYSQL_DATABASE: cash_manager_db
      MYSQL_USER: root
      MYSQL_PASSWORD: BoisdeCen2&*
    ports:
      - "3306:3306"
