version: '3'

services:

  backend:
    build: backend
    ports:
      - "5001:5001"
    restart: always
    container_name: "tdev-700-backend"
    networks:
      - network1

  frontend:
    build: frontend/CashManager
    restart: always
    container_name: "tdev-700-frontend"
    volumes:
      - "./frontend/CashManager:/app"
      - "/app/node_modules"
    depends_on:
      - backend
    ports:
      - "19006:19006"
    networks:
      - network1

#  frontend:
#    build: frontend/CashManager
#    restart: always
#    container_name: "tdev-700-frontend"
#    volumes:
#      - "./frontend/CashManager:/app"
#      - "/app/node_modules"
#    depends_on:
#      - backend
#    ports:
#      - "19006:19006"
#    networks:
#      - network1

networks:
  network1:

volumes:
  mysql_data:
