version: '3'

services:
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: BoisdeCen2&*
      MYSQL_DATABASE: cash_manager_db
      MYSQL_USER: root
      MYSQL_PASSWORD: BoisdeCen2&*
    ports:
      - "3306:3306"
