version: '3'

services:

  backend:
    build: backend
    ports:
      - "5001:5001"
    restart: always
    container_name: "tdev-700-backend"
    networks:
      - network1

  banque:
    build: banque
    ports:
      - "5002:5002"
    restart: always
    container_name: "tdev-700-banque"
    networks:
      - network1

  frontend:
    build: frontend/CashManager
    restart: always
    container_name: "tdev-700-frontend"
    volumes:
      - "./frontend/CashManager:/app"
      - "/app/node_modules"
    depends_on:
      - backend
      - banque
    ports:
      - "8082:8082"
      - "8081:8081"
    environment:
      - NODE_ENV=development
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.38.192
    networks:
      - network1

networks:
  network1:

